PINECONE_API_KEY="your API key"
PINECONE_ENVIRONMENT="gcp-starter"
PINECONE_INDEXNAME="legal-rag-bgem3"
PINECONE_NAMESPACE="bge_Law_0322"

OPENAI_API_KEY="your API key"
EMBEDDING_MODEL_NAME="BAAI/bge-m3"

TOP_K=10